# vMessage Config
# Thanks for downloading my plugin! I hope you like it!


messages:
  chat:
    # This is to give way to other plugins that may want to handle chat messages before vMessage does.

    # For example punishment plugins like LiteBans or LibertyBans may want to handle chat messages first.
    event-order: LAST
    enabled: true

    # Available placeholders: $player$, $message$, $server$, $prefix$, $suffix$, (custom luckperms metas), (PlaceholderAPI placeholders)
    format: '%prefix% <b>%player%</b>: %message%'

    # Whether to allow players to use MiniMessage in their messages
    # This may break your formatting, so it is recommended to keep this disabled.
    allow-mini-message: false
  join:
    enabled: true

    # Available placeholders: $player$, $server$, $prefix$, $suffix$, (custom luckperms metas)
    format: <dark_gray>(<green>+<dark_gray>) <gray>%player%
  leave:
    enabled: true

    # Available placeholders: $player$, $server$, $prefix$, $suffix$, (custom luckperms metas)
    format: <dark_gray>(<red>-<dark_gray>) <gray>%player%
  change:
    enabled: true

    # $player$ - Player
    # $old_server$ - Player's Previous Server
    # $new_server$ - Player's New Server
    # $prefix$ - LuckPerms Prefix
    # $suffix$ - LuckPerms Suffix
    format: <dark_gray>(<gold>•<dark_gray>) <gray>%player% <dark_gray>(<gold>%old_server%→%new_server%<dark_gray>)

commands:

  # /message, /msg, /tell, /whisper, /w (vmessage.command.message)
  message:
    enabled: true
    # Available placeholders: $sender$, $receiver$, $prefix$, $suffix$, (custom luckperms metas), (PlaceholderAPI placeholders)
    format:
      sender: "(<b><#00ffff>You</b> → <b><#00ffff>$receiver$</b>): $message$"
      receiver: "(<b><#00ffff>$sender$</b> → <b><#00ffff>You</b>): $message$"
    allow-mini-message: false
    allow-by-default: true
  reply:
    enabled: true
    allow-by-default: true
  broadcast:
    enabled: true
    format:
      # Available placeholders: $player$, $message$, $server$, $prefix$, $suffix$, (custom luckperms metas), (PlaceholderAPI placeholders)
      player: "<b><#00ffff>%player%</b>: <reset>%message%"
      # Available placeholders: $message$
      console: "<b><#00ffff>Console</b>: <reset>%message%"
    allow-mini-message: true
    allow-by-default: false
server-aliases:
  lobby: Lobby
  lobby1: Lobby
  lobby2: Lobby

# two types of integrations: "mute", "placeholder"
integrations:
  placeholder:
    luckperms:
      enabled: true
      # You must predefine your custom metas here to use them in your messages.
      custom-meta:
        custom1: meta_key1 # Used as &custom1&
        custom2: meta_key2 # Used as &custom2& etc.
    placeholderapi: # via PAPIProxyBridge
      enabled: true
      bridge-timeout: 500

settings:
  # Server name to use if retrieving the player's current server fails
  default-server-name: "Unknown"
  # Although this was a feature in vMessage 1.10.0-1.11.2, it is no longer supported in vMessage 2.0 and above.
  # This is because MiniMessage is now very integrated into AdventureAPI, FishyAPI and this plugin itself.
  # This may change in the future, if it is requested enough, but for now, it is not supported.
  legacy-color-codes: "NOT SUPPORTED"
  # Whether to check for updates on plugin load.
  # Will log a message to the console if an update is available.
  # This won't work when running a development build.
  check-for-updates: true