/*
 * vMessage
 * Copyright (c) 2025.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * See the LICENSE file in the project root for details.
 */

package off.szymon.vmessage;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.inject.Inject;
import com.velocitypowered.api.event.Subscribe;
import com.velocitypowered.api.event.proxy.ProxyInitializeEvent;
import com.velocitypowered.api.event.proxy.ProxyShutdownEvent;
import com.velocitypowered.api.plugin.Dependency;
import com.velocitypowered.api.plugin.Plugin;
import com.velocitypowered.api.plugin.PluginContainer;
import com.velocitypowered.api.plugin.annotation.DataDirectory;
import com.velocitypowered.api.proxy.ProxyServer;
import off.szymon.vmessage.cmd.CommandHandler;
import off.szymon.vmessage.compatibility.LuckPermsCompatibilityProvider;
import off.szymon.vmessage.compatibility.mute.EmptyMuteCompatibilityProvider;
import off.szymon.vmessage.compatibility.mute.LibertyBansCompatibilityProvider;
import off.szymon.vmessage.compatibility.mute.LiteBansCompatibilityProvider;
import off.szymon.vmessage.compatibility.mute.MutePluginCompatibilityProvider;
import off.szymon.vmessage.config.ConfigManager;
import org.bstats.charts.AdvancedPie;
import org.bstats.charts.SimplePie;
import org.bstats.velocity.Metrics;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;

import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URI;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;

@Plugin(
        id = "vmessage",
        name = "vMessage",
        // Your IDE may show an error here, but it will compile fine. This is generated during build. Run the generateVersion task if needed.
        version = off.szymon.vmessage.generated.Version.VERSION, // Generated by the build system if built with GitHub Actions
        description = "The #1 plugin for Velocity global message syncing",
        authors = {"SzymON_OFF"},
        url = "https://szymonoff.me/projects/vmessage.html",
        dependencies = {
                @Dependency(id = "signedvelocity", optional = true),
                @Dependency(id = "luckperms", optional = true),
                @Dependency(id = "libertybans", optional = true),
                @Dependency(id = "litebans", optional = true)
        }
)
public class VMessagePlugin {

    private static VMessagePlugin instance;

    private final ProxyServer server;
    private final Logger logger;
    private final File dataFolder;
    private final PluginContainer plugin;
    private final String name;
    private MutePluginCompatibilityProvider mutePluginCompatibilityProvider;
    private LuckPermsCompatibilityProvider lpCompatibilityProvider;
    private Broadcaster broadcaster;
    private final Metrics.Factory metricsFactory;

    @Inject
    public VMessagePlugin(ProxyServer server, Logger logger, @DataDirectory Path dataFolder, PluginContainer plugin, Metrics.Factory metricsFactory) {
        instance = this;

        this.server = server;
        this.logger = logger;
        this.dataFolder = new File(dataFolder.toFile().getParentFile(), this.getClass().getAnnotation(Plugin.class).name());
        this.plugin = plugin;
        this.metricsFactory = metricsFactory;

        this.name = this.getClass().getAnnotation(Plugin.class).name();
    }

    @Subscribe
    public void onProxyInitialization(ProxyInitializeEvent event) {
        this.onEnable();
    }

    @Subscribe
    public void onProxyShutdown(ProxyShutdownEvent event) {
        this.onDisable();
    }

    public void onEnable() {
        if (!server.getPluginManager().isLoaded("signedvelocity")) {
            logger.warn("SignedVelocity not detected! vMessage might not work properly without it.");
            logger.warn("Please consider installing SignedVelocity on the proxy and backends from https://modrinth.com/plugin/signedvelocity");
            logger.warn("Proceeding without it...");
        }
        new ConfigManager();

        /* LuckPerms */
        if (server.getPluginManager().isLoaded("luckperms")) {
            logger.info("LuckPerms detected, attempting to hook into it...");
            try {
                lpCompatibilityProvider = new LuckPermsCompatibilityProvider();
                logger.info("Successfully hooked into LuckPerms");
            } catch (Exception e) {
                lpCompatibilityProvider = null;
                logger.error("Failed to hook into LuckPerms, disabling support");
            }
        } else {
            logger.info("LuckPerms not detected, disabling support");
            lpCompatibilityProvider = null;
        }

        /* Mute Plugin Compatibility */
        Map<String, String> mutePlugins = Map.of("libertybans", "LibertyBans","litebans", "LiteBans");
        mutePluginCompatibilityProvider = new EmptyMuteCompatibilityProvider();
        logger.info("Checking for mute plugin compatibility...");
        for (Map.Entry<String, String> entry : mutePlugins.entrySet()) {
            String pluginName = entry.getKey();
            String displayName = entry.getValue();
            if (server.getPluginManager().isLoaded(pluginName)) {
                logger.info("{} detected, attempting to hook into it...", displayName);
                try {
                    switch (pluginName) {
                        case "libertybans":
                            mutePluginCompatibilityProvider = new LibertyBansCompatibilityProvider();
                            break;
                        case "litebans":
                            mutePluginCompatibilityProvider = new LiteBansCompatibilityProvider();
                            break;
                    }
                    logger.info("Successfully hooked into {}", displayName);
                    break;
                } catch (Exception e) {
                    mutePluginCompatibilityProvider = new EmptyMuteCompatibilityProvider();
                    logger.error("Failed to hook into {}, disabling support", displayName);
                }
            } else {
                logger.info("{} not detected, disabling support", displayName);
            }
        }

        broadcaster = new Broadcaster();
        server.getEventManager().register(this, new Listener());

        CommandHandler.registerCommands();

        checkForUpdates();

        Metrics metrics = metricsFactory.make(this, 27241);

        metrics.addCustomChart(new SimplePie("mute_plugin", () -> {
            String pluginName = "None";
            if (mutePluginCompatibilityProvider instanceof LibertyBansCompatibilityProvider) {
                pluginName = "LibertyBans";
            } else if (mutePluginCompatibilityProvider instanceof LiteBansCompatibilityProvider) {
                pluginName = "LiteBans";
            }
            return pluginName;
        }));
        metrics.addCustomChart(new AdvancedPie("enabled_features", () -> {
            Map<String, Integer> features = new HashMap<>();

            features.put("Chat Messages", ConfigManager.get().getConfig().getMessages().getChat().getEnabled() ? 1 : 0);
            features.put("Join Messages", ConfigManager.get().getConfig().getMessages().getJoin().getEnabled() ? 1 : 0);
            features.put("Leave Messages", ConfigManager.get().getConfig().getMessages().getLeave().getEnabled() ? 1 : 0);
            features.put("Server Change Messages", ConfigManager.get().getConfig().getMessages().getChange().getEnabled() ? 1 : 0);
            features.put("Broadcast Command", ConfigManager.get().getConfig().getCommands().getBroadcast().getEnabled() ? 1 : 0);
            features.put("Message Command", ConfigManager.get().getConfig().getCommands().getMessage().getEnabled() ? 1 : 0);
            features.put("Reply Command", ConfigManager.get().getConfig().getCommands().getMessage().getEnableReplyCommand() ? 1 : 0);
            features.put("LuckPerms Integration", lpCompatibilityProvider != null ? 1 : 0);
            return features;
        }));
    }

    public void onDisable() {
        System.out.println(this.name + " disabled");
    }

    public ProxyServer getServer() {
        return server;
    }

    public Logger getLogger() {
        return logger;
    }

    public File getDataFolder() {
        return dataFolder;
    }

    public static VMessagePlugin get() {
        return instance;
    }

    @Nullable("If LuckPerms is not loaded, this will return null")
    public LuckPermsCompatibilityProvider getLuckPermsCompatibilityProvider() {
        return lpCompatibilityProvider;
    }

    public MutePluginCompatibilityProvider getMutePluginCompatibilityProvider() {
        return mutePluginCompatibilityProvider;
    }

    public Broadcaster getBroadcaster() {
        return broadcaster;
    }

    public PluginContainer getPlugin() {
        return plugin;
    }

    private void checkForUpdates() {
        String pluginVersion = plugin.getDescription().getVersion().get();

        if (pluginVersion.toLowerCase().contains("dev")) {
            logger.info("Skipping update check (development build detected).");
            return;
        }

        logger.info("Checking for updates... (requesting Modrinth API)");
        logger.info("Current version: " + pluginVersion);

        try {
            String url = "https://api.modrinth.com/v2/project/ZIxTT2xI/version";

            HttpURLConnection connection = (HttpURLConnection) new URI(url).toURL().openConnection();
            connection.setRequestMethod("GET");
            connection.setRequestProperty("User-Agent", "vMessage-Plugin UpdateChecker");
            connection.connect();

            BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            JsonArray versions = new Gson().fromJson(reader, JsonArray.class);
            reader.close();

            String latestRelease = null;

            for (JsonElement element : versions) {
                JsonObject obj = element.getAsJsonObject();

                if (!obj.get("version_type").getAsString().equalsIgnoreCase("release"))
                    continue;

                String version = obj.get("version_number").getAsString();

                if (latestRelease == null || isVersionGreater(version, latestRelease))
                    latestRelease = version;
            }

            if (latestRelease == null) {
                logger.warn("No Modrinth release versions found.");
                return;
            }

            logger.info("Latest release: " + latestRelease);

            if (isVersionGreater(latestRelease, pluginVersion)) {
                logger.info("New version available on Modrinth.");
                logger.info("Download it from: https://modrinth.com/plugin/vmessage/version/" + latestRelease);
            } else if (latestRelease.equals(pluginVersion)) {
                logger.info("You are running the latest version.");
            } else {
                logger.info("You are running a development version ahead of the latest release.");
            }
        } catch (Exception ex) {
            logger.warn("Failed to check for updates: ", ex);
        }
    }

    private boolean isVersionGreater(String a, String b) {
        String[] as = a.split("\\.");
        String[] bs = b.split("\\.");

        int max = Math.max(as.length, bs.length);

        for (int i = 0; i < max; i++) {
            int ai = (i < as.length) ? parseDigit(as[i]) : 0;
            int bi = (i < bs.length) ? parseDigit(bs[i]) : 0;

            if (ai > bi) return true;
            if (ai < bi) return false;
        }
        return false;
    }

    private int parseDigit(String s) {
        try {
            return Integer.parseInt(s.replaceAll("[^0-9]", ""));
        } catch (NumberFormatException e) {
            return 0;
        }
    }

}
