# vMessage Configuration File
# Thanks for downloading my plugin! I hope you like it!
# MiniMessage is supported for formatting in all messages.
# Placeholders are parsed before MiniMessage so you can use them in your format.
# For in-depth explanation of the configuration options, visit: https://github.com/szymon-off/vMessage/wiki/Configuration-(config.yml)
#
# ⚠️ If you have used vMessage before v1.8.0, the contents of this file may be malformed ⚠️

messages:
  chat:
    enabled: true

    # %player% - Player
    # %message% - Message
    # %server% - Player's Current Server
    # %prefix% - LuckPerms Prefix
    # %suffix% - LuckPerms Suffix
    format: '%prefix% <b>%player%:</b> %message%'

    # Whether to allow players to use MiniMessage in their messages
    allow-mini-message: false

    # The message to send when a muted player tries to send a message
    # %player% - Player
    # %message% - Message
    # %server% - Player's Current Server
    # %prefix% - LuckPerms Prefix
    # %suffix% - LuckPerms Suffix
    # %reason% - Reason for muting
    # %end-date% - End date of the mute
    # %moderator% - Moderator who muted the player
    muted-message: <red>You are muted and cannot send messages.</red>
  join:
    enabled: true

    # %player% - Player
    # %server% - Player's Current Server
    # %prefix% - LuckPerms Prefix
    # %suffix% - LuckPerms Suffix
    format: <dark_gray>(<green>+<dark_gray>) <gray>%player%
  leave:
    enabled: true

    # %player% - Player
    # %server% - Player's Last Server
    # %prefix% - LuckPerms Prefix
    # %suffix% - LuckPerms Suffix
    format: <dark_gray>(<red>-<dark_gray>) <gray>%player%
  change:
    enabled: true

    # %player% - Player
    # %old_server% - Player's Previous Server
    # %new_server% - Player's New Server
    # %prefix% - LuckPerms Prefix
    # %suffix% - LuckPerms Suffix
    format: <dark_gray>(<gold>•<dark_gray>) <gray>%player% <dark_gray>(<gold>%old_server%→%new_server%<dark_gray>)
commands:
  # /broadcast, /bcast, /bc
  broadcast:
    enabled: true

    # %message% - Message
    format: <bold><#00ffff>Server:<reset> %message%

  # /message, /msg, /whisper, /w
  message:
    enabled: true

    # %sender% - Sender
    # %receiver% - Receiver
    # %message% - Message
    # %sender-server% - Sender's Current Server
    # %receiver-server% - Receiver's Current Server
    # %sender-prefix% - Sender's LuckPerms Prefix
    # %sender-suffix% - Sender's LuckPerms Suffix
    # %receiver-prefix% - Receiver's LuckPerms Prefix
    # %receiver-suffix% - Receiver's LuckPerms Suffix
    # Custom meta placeholders are currently not supported for this option
    format:
      sender: '<b>(<#00ffff>You </#00ffff>→ <#00ffff>%receiver%</#00ffff>): </b>%message%'
      receiver: '<b>(<#00ffff>%sender% </#00ffff>→ <#00ffff>You</#00ffff>): </b>%message%'

    # Whether to allow players to use MiniMessage in their private messages
    allow-mini-message: false

    # Whether to enable the /reply command
    # It will reply to the last person who sent you a message
    enable-reply-command: true

# If you want to use additional LuckPerms meta values you can add them here
# You can then use them in placeholder format like this: &custom_name& [AMPERSAND not PERCENT]
luck-perms-meta:
  custom-name1: meta_key1
  custom-name2: meta_key2

# If you want to display a different name for a server you can add it here
# It will then be used in the messages above instead of the server's actual name
server-aliases:
  lobby: Lobby
  lobby1: Lobby
  lobby2: Lobby
